apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'node-service'
        static_configs:
          - targets: ['registration-service:3000']

      - job_name: 'python-service'
        static_configs:
          - targets: ['notification-service:5000']

      - job_name: 'dotnet-service'
        static_configs:
          - targets: ['customer-service:5288']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
