{
 "title": "Microservices Overview",
 "tags": [
  "docker",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "📈 Node.js Request Count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{method}} {{path}}" }
   ]
  },
  {
   "title": "📧 Emails Sent (Python)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "emails_sent_total", "legendFormat": "emails" }
   ]
  },
  {
   "title": "🧠 Kafka Events Received (Python)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "kafka_events_received_total", "legendFormat": "events" }
   ]
  },
  {
   "title": "📊 .NET HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "http_request_duration_seconds", "legendFormat": "{{verb}}" }
   ]
  }
 ]
}