apiVersion: v1
data:
  init-db.sql: |-
    CREATE TABLE IF NOT EXISTS users (
                                         id SERIAL PRIMARY KEY,
                                         name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: postgres
  name: postgres-cm1
