version: '3.8'

services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend
      - backend-network

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  backend-network:
    external: true