apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.override.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: notification-service
