apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.customer-service.yml -o k8s-customer/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: customer-service
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.customer-service.yml -o k8s-customer/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: customer-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: KAFKA_BROKER
              value: kafka-broker:29092
            - name: POSTGRES_DB
              value: registration_db
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_USER
              value: admin
          image: customer-service
          name: customer-service
          ports:
            - containerPort: 5288
              protocol: TCP
      restartPolicy: Always
