version: '3.8'

services:
  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile
    container_name: customer-service
    ports:
      - "5288:5288"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KAFKA_BROKER=kafka-broker:29092
      - POSTGRES_HOST=postgres-service
      - POSTGRES_DB=registration_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - backend

networks:
  backend:
    driver: bridge
