version: '3.8'

services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "5288:5288"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DATABASE_URL=${DATABASE_URL}
      - KAFKA_BROKER=${KAFKA_BROKER}
    networks:
      - backend-network

networks:
  backend-network:
    external: true
